#version: '3.8'

services:
  bot:
    build: .
    env_file:
     - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
